flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- digestive-functors-0.8.3.0
- digestive-functors-aeson-1.1.22
- heroku-0.1.2.3
- primitive-0.6.4.0
- persistent-migration-0.1.0
resolver: lts-10.4
